// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/28/2026, 1:01:53 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/macbookpro/Documents/work/intranet/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookpro/Documents/work/intranet/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookpro/Documents/work/intranet/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookpro/Documents/work/intranet/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookpro/Documents/work/intranet/plugins/**/*.{js,ts,mjs}","/Users/macbookpro/Documents/work/intranet/composables/**/*.{js,ts,mjs}","/Users/macbookpro/Documents/work/intranet/utils/**/*.{js,ts,mjs}","/Users/macbookpro/Documents/work/intranet/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookpro/Documents/work/intranet/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookpro/Documents/work/intranet/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/macbookpro/Documents/work/intranet/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;